[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mappingservice-plugincore"
version = "1.0.0-rc1"
description = "Shared core functionalities for KITDM mapping service python plugins"
requires-python = ">=3.9"
license-files = ["LICENSE"]
authors = [
  { name = "Germaine Götzelmann", email = "germaine.goetzelmann@kit.edu" }
]
dependencies = [
  "pydantic"
]
optional-dependencies = [
  "pytest"
]

[project.urls]
Homepage = "https://github.com/GGoetzelmann/mappingservice_plugincore"
Source = "https://github.com/GGoetzelmann/mappingservice_plugincore"
